- name: nginx install and run
  hosts: frontend
  become: yes # sudo access
  tasks:
  - name: install nginx server
    ansible.builtin.package: # module to install packages it will work for all linux os dosen't care about yum or apt or dnt it is handle by ansible itself, packages will install all the os 
      name: nginx
      state: present